[package]
name = "bar-scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
futures-lite = "2.6.0"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["macros", "rt", "sync", "time"] }
zbus = { version = "5.6.0", features = ["tokio"] }

[profile.release]
opt-level = 3
strip = true
codegen-units = 1
lto = "fat"
panic = "abort"
