[package]
name = "bar-scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["macros", "rt", "sync", "time"] }
zbus = { version = "5.6.0", features = ["tokio"] }
